# Generated by Django 4.2.1 on 2023-07-07 00:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gqf', '0002_alter_gqf_code_alter_gqf_enabled_alter_gqf_name'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='associated_facilities',
            field=models.ManyToManyField(blank=True, to='gqf.gqf', verbose_name='Associated Facilities'),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='password_expiry_date',
            field=models.DateField(default=datetime.date(1, 7, 7), verbose_name='Password Expiry'),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='password_expiry_notification_date',
            field=models.DateField(default=datetime.date(1, 6, 30), verbose_name='Password Expiry Notification'),
        ),
    ]
