# Generated by Django 4.2.1 on 2023-07-18 01:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_systemuser_associated_facilities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='password_expiry_date',
            field=models.DateField(default=datetime.date(1, 7, 18), verbose_name='Password Expiry'),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='password_expiry_notification_date',
            field=models.DateField(default=datetime.date(1, 7, 11), verbose_name='Password Expiry Notification'),
        ),
    ]
