branch-defaults:
  main:
    environment: gms-project-env
    group_suffix: null
  master:
    environment: gms-project-env
global:
  application_name: gms_project
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.11
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
