# Generated by Django 4.2.1 on 2023-06-12 03:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gqf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventory_status',
            fields=[
                ('status', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=80, null=True)),
                ('value', models.IntegerField(default=99)),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
            options={
                'db_table': 'tbl_cbk_inventory_status',
                'ordering': ('value',),
            },
        ),
        migrations.CreateModel(
            name='suite_type',
            fields=[
                ('suite_type', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('sortorder', models.IntegerField(default=0)),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
            options={
                'db_table': 'tbl_cbk_suite_type',
                'ordering': ('sortorder',),
            },
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('room_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=80)),
                ('room_twinroom', models.BooleanField(default=False)),
                ('room_modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('room_created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('room_hotel', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gqf.gqf')),
                ('room_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory_status')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.suite_type')),
            ],
            options={
                'db_table': 'tbl_cbk_room_inventory',
            },
        ),
    ]
