# Generated by Django 4.2.1 on 2023-06-26 02:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gqf', '0002_alter_gqf_code_alter_gqf_enabled_alter_gqf_name'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory_status',
            name='description',
            field=models.CharField(blank=True, db_column='description', max_length=80, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='inventory_status',
            name='status',
            field=models.CharField(db_column='status', max_length=40, primary_key=True, serialize=False, verbose_name='Room Status'),
        ),
        migrations.AlterField(
            model_name='inventory_status',
            name='value',
            field=models.IntegerField(db_comment='For sorting and display purpose', default=99),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_hotel',
            field=models.ForeignKey(db_column='room_hotel', on_delete=django.db.models.deletion.CASCADE, to='gqf.gqf', verbose_name='Facility Name'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.UUIDField(db_column='room_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Room ID'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.CharField(db_column='room_name', max_length=80, verbose_name='Room Name'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_status',
            field=models.ForeignKey(db_column='room_status', on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.inventory_status', verbose_name='Room Status'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_twinroom',
            field=models.BooleanField(db_column='room_twinroom', default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(db_column='room_type', on_delete=django.db.models.deletion.RESTRICT, to='inventory.suite_type', verbose_name='Suite Type'),
        ),
        migrations.AlterField(
            model_name='suite_type',
            name='description',
            field=models.CharField(blank=True, db_column='description', max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='suite_type',
            name='sortorder',
            field=models.IntegerField(db_column='sortorder', db_comment='For sorting and display purpose', default=0, verbose_name='Sort order'),
        ),
        migrations.AlterField(
            model_name='suite_type',
            name='suite_type',
            field=models.CharField(db_column='suite_type', max_length=40, primary_key=True, serialize=False, verbose_name='Suite Type'),
        ),
    ]
