# Generated by Django 4.2.1 on 2023-07-07 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_status_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_twinroom',
            field=models.BooleanField(db_column='room_twinroom', default=False, verbose_name='Twin Room'),
        ),
    ]
