# Generated by Django 4.2.1 on 2023-06-12 03:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='person_type',
            fields=[
                ('guest_type', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Guest Type')),
                ('guest_type_description', models.CharField(blank=True, max_length=80, null=True, verbose_name='Description')),
                ('guest_type_sortorder', models.IntegerField(default=0)),
                ('guest_type_modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('guest_type_created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
            options={
                'db_table': 'tbl_cbk_guest_type',
                'ordering': ('guest_type_sortorder',),
            },
        ),
        migrations.CreateModel(
            name='hotel_guest',
            fields=[
                ('guest_id', models.CharField(max_length=9, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(9)], verbose_name='NRIC/ FIN')),
                ('guest_passport_number', models.CharField(blank=True, max_length=13, null=True, verbose_name='Passport number')),
                ('guest_name', models.CharField(max_length=80, verbose_name='Guest name')),
                ('guest_date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('guest_comm_dweller', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Community Dweller')),
                ('guest_location', models.CharField(default='Facility', max_length=255, verbose_name='Current Location')),
                ('guest_modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('guest_created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('guest_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='guests.person_type')),
            ],
            options={
                'db_table': 'tbl_cbk_hotel_guests',
            },
        ),
    ]
