# Generated by Django 4.2.1 on 2023-06-13 06:32

from django.db import migrations
import guests.models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_guest',
            name='guest_comm_dweller',
            field=guests.models.YesNoField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Community Dweller'),
        ),
    ]
