# Generated by Django 4.2.1 on 2023-06-26 02:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import guests.models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0004_rename_guest_hotel_guest_guest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_guest',
            name='guest_comm_dweller',
            field=guests.models.YesNoField(choices=[(True, 'Yes'), (False, 'No')], db_column='guest_comm_dweller', default=True, verbose_name='Community Dweller'),
        ),
        migrations.AlterField(
            model_name='hotel_guest',
            name='guest_date_of_birth',
            field=models.DateField(db_column='guest_date_of_birth', verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='hotel_guest',
            name='guest_id',
            field=models.CharField(db_column='guest_id', max_length=9, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(9)], verbose_name='NRIC/ FIN'),
        ),
        migrations.AlterField(
            model_name='hotel_guest',
            name='guest_location',
            field=models.CharField(db_column='guest_location', default='Facility', max_length=255, verbose_name='Current Location'),
        ),
        migrations.AlterField(
            model_name='hotel_guest',
            name='guest_name',
            field=models.CharField(db_column='guest_name', max_length=80, verbose_name='Guest name'),
        ),
        migrations.AlterField(
            model_name='hotel_guest',
            name='guest_passport_number',
            field=models.CharField(blank=True, db_column='guest_passport_number', max_length=13, null=True, verbose_name='Passport number'),
        ),
        migrations.AlterField(
            model_name='hotel_guest',
            name='guest_type',
            field=models.ForeignKey(db_column='guest_type', on_delete=django.db.models.deletion.RESTRICT, to='guests.person_type', verbose_name='Guest Type'),
        ),
    ]
