# Generated by Django 4.2.1 on 2023-07-07 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0005_alter_hotel_guest_guest_comm_dweller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_guest',
            name='guest_created',
            field=models.DateTimeField(auto_now_add=True, db_column='guest_created', verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='hotel_guest',
            name='guest_modified',
            field=models.DateTimeField(auto_now=True, db_column='guest_modified', verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='person_type',
            name='guest_type',
            field=models.CharField(db_column='guest_type', max_length=40, primary_key=True, serialize=False, verbose_name='Guest Type'),
        ),
        migrations.AlterField(
            model_name='person_type',
            name='guest_type_description',
            field=models.CharField(blank=True, db_column='guest_type_description', max_length=80, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='person_type',
            name='guest_type_sortorder',
            field=models.IntegerField(db_column='guest_type_sortorder', default=0, verbose_name='Sort Order'),
        ),
    ]
