# Generated by Django 4.2.1 on 2023-06-12 03:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('guests', '0001_initial'),
        ('gqf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='guest_transaction',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Reservation ID')),
                ('trans_date_checkin', models.DateTimeField(blank=True, null=True, verbose_name='Check-in')),
                ('trans_date_checkin_planned', models.DateField(blank=True, null=True, verbose_name='Expected Check-in')),
                ('trans_date_checkout', models.DateTimeField(blank=True, null=True, verbose_name='Check-out')),
                ('trans_date_checkout_planned', models.DateField(blank=True, null=True, verbose_name='Expected Check-out')),
                ('trans_remarks', models.TextField(blank=True, max_length=8192, null=True, verbose_name='Remarks')),
                ('trans_modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('trans_created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('trans_checkin_hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='gqf.gqf', verbose_name='Facility Name')),
                ('trans_guest_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='guests.hotel_guest', verbose_name='Guest ID')),
                ('trans_room_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='inventory.room', verbose_name='Room ID')),
            ],
            options={
                'db_table': 'tbl_cbk_guest_transaction',
            },
        ),
    ]
