# Generated by Django 4.2.1 on 2023-06-21 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest_transaction',
            old_name='trans_guest_id',
            new_name='trans_guest',
        ),
        migrations.RenameField(
            model_name='guest_transaction',
            old_name='trans_room_id',
            new_name='trans_room',
        ),
        migrations.RenameField(
            model_name='guest_transaction',
            old_name='transaction_id',
            new_name='transaction',
        ),
    ]
