# Generated by Django 4.2.1 on 2023-06-21 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gms', '0002_rename_trans_guest_id_guest_transaction_trans_guest_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest_transaction',
            old_name='transaction',
            new_name='transaction_id',
        ),
    ]
