# Generated by Django 4.2.1 on 2023-06-26 02:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gqf', '0001_initial'),
        ('gms', '0003_rename_transaction_guest_transaction_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest_transaction',
            name='trans_guest',
            field=models.ForeignKey(blank=True, db_column='trans_guest_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to='guests.hotel_guest', verbose_name='Guest ID'),
        ),
        migrations.RenameField(
            model_name='guest_transaction',
            old_name='trans_guest',
            new_name='trans_guest_id',
        ),
        migrations.AlterField(
            model_name='guest_transaction',
            name='trans_room',
            field=models.ForeignKey(blank=True, db_column='trans_room_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to='inventory.room', verbose_name='Room ID'),
        ),
        migrations.RenameField(
            model_name='guest_transaction',
            old_name='trans_room',
            new_name='trans_room_id',
        ),
        migrations.AlterField(
            model_name='guest_transaction',
            name='trans_checkin_hotel',
            field=models.ForeignKey(blank=True, db_column='trans_checkin_hotel', null=True, on_delete=django.db.models.deletion.RESTRICT, to='gqf.gqf', verbose_name='Facility Name'),
        ),
        migrations.AlterField(
            model_name='guest_transaction',
            name='trans_date_checkin',
            field=models.DateTimeField(blank=True, db_column='trans_date_checkin', null=True, verbose_name='Check-in'),
        ),
        migrations.AlterField(
            model_name='guest_transaction',
            name='trans_date_checkin_planned',
            field=models.DateField(blank=True, db_column='trans_date_checkin_planned', null=True, verbose_name='Expected Check-in'),
        ),
        migrations.AlterField(
            model_name='guest_transaction',
            name='trans_date_checkout',
            field=models.DateTimeField(blank=True, db_column='trans_date_checkout', null=True, verbose_name='Check-out'),
        ),
        migrations.AlterField(
            model_name='guest_transaction',
            name='trans_date_checkout_planned',
            field=models.DateField(blank=True, db_column='trans_date_checkout_planned', null=True, verbose_name='Expected Check-out'),
        ),
        migrations.AlterField(
            model_name='guest_transaction',
            name='trans_remarks',
            field=models.TextField(blank=True, db_column='trans_remarks', max_length=8192, null=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='guest_transaction',
            name='transaction_id',
            field=models.UUIDField(db_column='transaction_id', default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Reservation ID'),
        ),
    ]
