# Generated by Django 4.2.1 on 2023-06-26 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0005_alter_hotel_guest_guest_comm_dweller_and_more'),
        ('gms', '0004_alter_guest_transaction_trans_guest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest_transaction',
            name='trans_guest_id',
            field=models.ForeignKey(db_column='trans_guest_id', on_delete=django.db.models.deletion.RESTRICT, to='guests.hotel_guest', verbose_name='Guest ID'),
        ),
    ]
