# Generated by Django 4.2.1 on 2023-06-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GQF',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Facility Code')),
                ('name', models.CharField(max_length=80, verbose_name='Facility Name')),
                ('enabled', models.BooleanField(default=False, verbose_name='In operation')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
            options={
                'db_table': 'tbl_cbk_gqf',
                'ordering': ('code',),
            },
        ),
    ]
