# Generated by Django 4.2.1 on 2023-06-26 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gqf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gqf',
            name='code',
            field=models.CharField(db_column='code', max_length=8, primary_key=True, serialize=False, verbose_name='Facility Code'),
        ),
        migrations.AlterField(
            model_name='gqf',
            name='enabled',
            field=models.BooleanField(db_column='enabled', default=False, verbose_name='In operation'),
        ),
        migrations.AlterField(
            model_name='gqf',
            name='name',
            field=models.CharField(db_column='name', max_length=80, verbose_name='Facility Name'),
        ),
    ]
